modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/TheIllusiveC4/Colytra/issues"
logoFile="${mod_icon}"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_url}"
authors="${mod_author}"
description='''
${mod_description}
'''
[[dependencies.colytra]]
    modId="forge"
    mandatory=true
    versionRange="[28.0.45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.colytra]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4,1.15)"
    ordering="NONE"
    side="BOTH"
[[dependencies.colytra]]
    modId="caelus"
    mandatory=true
    versionRange="[FORGE-1.14.4-0.10,)"
    ordering="NONE"
    side="BOTH"